# Generated by Django 4.1.3 on 2022-11-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25, verbose_name="Prenom")),
                ("last_name", models.CharField(max_length=25, verbose_name="Nom")),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                ("mobile", models.CharField(max_length=20, verbose_name="Mobile")),
                (
                    "compagny_name",
                    models.CharField(max_length=250, verbose_name="Mobile"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(verbose_name="Date de mise a jour"),
                ),
                (
                    "converted_client",
                    models.BooleanField(default=False, verbose_name="Client converti"),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendeur",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
    ]
