# Generated by Django 4.1.3 on 2022-11-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Client", "0002_alter_client_sales_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, max_length=100, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mobile"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
    ]
