# Generated by Django 4.1.3 on 2022-11-24 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Client", "0002_alter_client_sales_contact"),
        ("Event", "0002_alter_contract_amount_alter_contract_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="sales_contact",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_sales_contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_client",
                to="Client.client",
                verbose_name="Client",
            ),
        ),
    ]
