# Generated by Django 4.1.3 on 2022-11-24 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Event", "0003_alter_contract_sales_contact_alter_event_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="sales_contact",
            field=models.ForeignKey(
                limit_choices_to={"group__name": "Vente"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contract_sales_contact",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendeur",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="support_contact",
            field=models.ForeignKey(
                limit_choices_to={"group__name": "Support"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Support",
            ),
        ),
    ]
